### ISSUE TITLE
Add flag for self-signed SSL certificates in config/settings.yml

### ISSUE THREAD

**Issue by gadamo** [echoCTF/echoCTF-gw#2]
A flag in `config/settings.yml` for self signed certs, triggering different actions in `includes/openssl-certs.yml`. 

Also a comment above the flag in `config/settings.yml`, mentioning the predefined locations of certificate files, as expected by `includes/openssl-certs.yml`.

**Comment by proditis** [comment]
This has been fixed. A flag exists that does just that.
