### ISSUE TITLE
Moderators interface enforces a gateway IP

### ISSUE THREAD

**Issue by gadamo** [echoCTF/echoCTF-gw#3]
Set in `config/settings.yml`:

https://github.com/echoCTF/echoCTF-gw/blob/a526d16d2562f688ddbc31cc16edce9c258248ea/config/settings.yml#L25

Route enforced here:

https://github.com/echoCTF/echoCTF-gw/blob/a526d16d2562f688ddbc31cc16edce9c258248ea/config/settings.yml#L81

Also propagated in ctf_settings in `config/moderators.yml`:

https://github.com/echoCTF/echoCTF-gw/blob/a526d16d2562f688ddbc31cc16edce9c258248ea/config/moderators.yml#L36

**Comment by proditis** [comment]
This requires the following:
* introduction of a hostname.if jinja2 template
* replace settings.yml interface hardcoded values into yml format
* replace hostnames creation with the template

**Comment by proditis** [comment]
fixed but forgotten
