### ISSUE TITLE
Plain syslog by default

### ISSUE THREAD

**Issue by gadamo** [echoCTF/echoCTF-gw#4]
Currently, rc configuration will start syslog_ng as default syslog server

https://github.com/echoCTF/echoCTF-gw/blob/a526d16d2562f688ddbc31cc16edce9c258248ea/config/applications.yml#L31

and disables syslog

https://github.com/echoCTF/echoCTF-gw/blob/a526d16d2562f688ddbc31cc16edce9c258248ea/config/settings.yml#L115

It looks safer to reverse this setting and use the builtin syslog server by default.

**Comment by proditis** [comment]
we're back to the roots
